version: '3.8'
services:
  django_app:
    build: .
    container_name: django_OrderService
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy  # Wait for database
    environment:
      - DATABASE_URL=postgres://order_user:Sonu%40123@db:5432/order_service_db
      - KAFKA_BROKER=kafka:9092
    networks:
      - microservices_net

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: Sonu@123
      POSTGRES_DB: order_service_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices_net

volumes:
  postgres_data:

networks:
  microservices_net:
    driver: bridge
